In [1]:
import numpy as np
import pandas as pd

In [4]:
data = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
data.shape

(1043, 6)

In [6]:
data = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_header=2)
data

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [7]:
data = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_footer=2)
data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [9]:
data = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(0,1,5))
data

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [10]:
data = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(5,0,1))
data

array([[13621.,  2000.,    40.],
       [15041.,  2000.,    40.],
       [15340.,  1000.,    40.],
       ...,
       [16600.,    nan,    40.],
       [15600.,  1000.,    40.],
       [16600.,  2000.,    40.]])

In [11]:
new_data = pd.read_json('Lending-company.json')
new_data

Loan ID String_ID    Product CustomerGender      Location    Region  \
0           1      id_1  Product B           Male    Location 2  Region 2   
1           2      id_2  Product B           Male    Location 3  Region 3   
2           3      id_3  Product C         Female    Location 5  Region 5   
3           4      id_4  Product B           Male    Location 6  Region 1   
4           5      id_5  Product D         Female    Location 7  Region 2   
...       ...       ...        ...            ...           ...       ...   
1038     1039   id_1039  Product B         Female   Location 39  Region 6   
1039     1040   id_1040  Product B           Male   Location 50  Region 1   
1040     1041   id_1041  Product B           Male   Location 23  Region 4   
1041     1042   id_1042  Product C   NotSpecified   Location 52  Region 6   
1042     1043   id_1043  Product B         Female  Location 142  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDays  AmountPaid30  \
0          16600    7/4/2014     2000         40        365          3121   
1          16600    1/2/2015     2000         40        365          3061   
2          15600   12/8/2012     1000         40        365          2160   
3          16600   2/20/2015     2000         40        365          3041   
4          20250  10/28/2013     2000         50        365          3470   
...          ...         ...      ...        ...        ...           ...   
1038       16600  12/29/2014     2000         40        365          3401   
1039       16600   3/28/2014     2000         40        365          4240   
1040       16600   4/26/2014     2000         40        365          4201   
1041       15600  10/25/2012     1000         40        365          2080   
1042       16600   5/15/2015     2000         40        365          4601   

      AmountPaid60  AmountPaid360     LoanStatus360  
0             4241          13621            Active  
1             4171          15041            Active  
2             3280          15340              None  
3             4241          15321            Active  
4             4820          13720            Active  
...            ...            ...               ...  
1038          4601          16600  Finished Payment  
1039          5440          16600  Finished Payment  
1040          5001          16600  Finished Payment  
1041          3320          15600  Finished Payment  
1042          4601          16600  Finished Payment  

[1043 rows x 15 columns]

# save the files using pandas 

In [13]:
new_data.to_csv('My-csv-file.csv')

In [14]:
new_data.to_json('My-json-file.json')

In [16]:
new_data.to_excel('My-excel-file.xlsx')

In [18]:
new_data.to_excel('My-excel-file1.xlsx',index=False)